# Generated by Django 4.1.4 on 2023-01-02 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_picture",
            field=models.ImageField(default="default_book_cover.png", upload_to=""),
        ),
    ]
